# -*- coding: utf-8 -*-
"""19092025_Data_Label.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMBOUQuVnv_uQ--BHC8ILDSzb2Lv_eqP
"""

import numpy as np
import pandas as pd

data1 = pd.read_csv('/content/sensor_data_nRF_IMU_1_19092025_164551_not_labelled.csv')
data2 = pd.read_csv('/content/sensor_data_nRF_IMU_2_19092025_164551_labelled.csv')

data1.head()

data2.head()

data2 = data2.drop('Unnamed: 11', axis=1)
data2.head()

data2.dropna(inplace=True)
data2.head()

data = pd.merge(data1, data2, on=['TimeStamp'])
data.head()

data.info()

data.to_csv('19092025_labelled.csv', index=False)