# -*- coding: utf-8 -*-
"""23092025_Data_Label.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMBOUQuVnv_uQ--BHC8ILDSzb2Lv_eqP
"""

import numpy as np
import pandas as pd

data1 = pd.read_csv('/content/sensor_data_nRF_IMU_1_23092025_120831 copy.csv')
data2 = pd.read_csv('/content/sensor_data_nRF_IMU_2_23092025_120831 copy.csv')

data1.head()

data2.head()

data1.dropna(inplace=True)
data1.head()

data = pd.merge(data1, data2, on=['TimeStamp'])
data.head()

data.info()

data.to_csv('23092025_labelled.csv', index=False)